version: "3"

services:
  backend:
    container_name: api
    build: ./backend
    networks:
      - api-db
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - 4000:3000
    depends_on:
      - database
  database:
    container_name: database
    image: postgres:12
    networks:
      - api-db
    env_file:
      - ./.env
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
  frontend:
    container_name: anf-frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - 8081:80

volumes:
  pg_data:

networks:
  api-db: {}
