version: "3"

services:
  frontend:
    container_name: anf-frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
  backend:
    container_name: anf-backend
    build: ./backend
    networks:
      - backend-database
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "4000:3000"
    depends_on:
      - database
  database:
    container_name: anf-db
    image: postgres:12
    networks:
      - backend-database
    env_file:
      - ./.env
    restart: unless-stopped
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
volumes:
  pg_data:
networks:
  backend-database: {}
